exp_path: "/home/rdaneel/my_exp_PBS0627/"
# exp_path: "/home/rdaneel/my_exp_socs2022/"
# exp_path: "/home/rdaneel/my_exp/"
ins_num: 25
time_limit: 60
set_title: true
set_legend: true
plot_ci: false
plot_std: false

maps:
  # - name: "random-32-32-20"
  #   label: Random
  #   scens:
  #     - even
  #     - random
  #   num_of_agents:
  #     - 10
  #     - 20
  #     - 30
  #     - 40
  #     - 50
  #     - 60
  #     - 70
  #     - 80
  #     - 90
  #     - 100

  # - name: "warehouse-20-40-10-2-1"
  #   label: Warehouse
  #   scens:
  #     - even
  #     - random
  #   num_of_agents:
  #     - 20
  #     - 40
  #     - 60
  #     - 80
  #     - 100
  #     - 120
  #     - 140
  #     - 160
  #     - 180
  #     - 200

  # - name: "den520d"
  #   label: Den520d
  #   scens:
  #     - even
  #     - random
  #   num_of_agents:
  #     - 20
  #     - 40
  #     - 60
  #     - 80
  #     - 100
  #     - 120
  #     - 140
  #     - 160
  #     - 180
  #     - 200

  # - name: "maze-32-32-2"
  #   label: Maze
  #   scens:
  #     - even
  #     - random
  #   num_of_agents:
  #     - 10
  #     - 20
  #     - 30
  #     - 40
  #     - 50
  #     - 60
  #     - 70
  #     - 80
  #     - 90
  #     - 100

  - name: "room-32-32-4"
    label: Room
    scens:
      - even
      - random
    num_of_agents:
      - 10
      - 20
      - 30
      - 40
      - 50
      - 60
  #     - 70
  #     - 80
  #     - 90
  #     - 100

solvers:
  # - name: "PBS0"
  #   label: "PBS"
  #   color: "grey"
  #   marker: "P"

  # - name: "PBS1"
  #   label: "PBS(Random)"
  #   color: "purple"
  #   marker: "d"

  - name: "PBS1_min_runtime"
    label: "PBS(best)"
    color: "grey"
    marker: "P"

  - name: "PBS2"
    label: "PBS(Earliest)"
    color: "deepskyblue"
    marker: "o"

  # - name: "PBS3"
  #   label: "PBS(Min PA)"
  #   color: 'deepskyblue'
  #   marker: 'o'

  - name: "PBS4"
    label: "PBS(Max PA)"
    color: 'gold'
    marker: '^'

  # - name: "PBS5"
  #   label: "PBS(BFS)"
  #   color: 'orange'
  #   marker: '*'

  # - name: "PBS6"
  #   label: "PBS(DFS)"
  #   color: 'pink'
  #   marker: 'H'

  # - name: "PBS7"
  #   label: "PBS(Min cons)"
  #   color: 'red'
  #   marker: '>'

  - name: "PBS8"
    label: "PBS(Max cons)"
    color: 'brown'
    marker: 'X'