exp_path: "/home/rdaneel/my_exp_PBS0627/"
# exp_path: "/home/rdaneel/my_exp_socs2022/"
# exp_path: "/home/rdaneel/my_exp/"
ins_num: 25
time_limit: 60
set_title: true
set_legend: true
plot_ci: false
plot_std: false

maps:
  # - name: "den520d"
  #   label: Den520d
  #   scens:
  #     - even
  #     - random
  #   num_of_agents:
  #     - 20
  #     - 40
  #     - 60
  #     - 80
  #     - 100
  #     - 120
  #     - 140
  #     - 160
  #     - 180
  #     - 200

  # - name: "warehouse-20-40-10-2-1"
  #   label: Warehouse
  #   scens:
  #     - even
  #     - random
  #   num_of_agents:
  #     - 20
  #     - 40
  #     - 60
  #     - 80
  #     - 100
  #     - 120
  #     - 140
  #     - 160
  #     - 180
  #     - 200

  - name: "maze-32-32-2"
    label: Maze
    scens:
      - even
      - random
    num_of_agents:
      - 10
      - 20
      - 30
      - 40
      - 50
      - 60
      # - 70
      # - 80
      # - 90
      # - 100

  # - name: "random-32-32-20"
  #   label: Random
  #   scens:
  #     - even
  #     - random
  #   num_of_agents:
  #     - 10
  #     - 20
  #     - 30
  #     - 40
  #     - 50
  #     - 60
  #     - 70
  #     - 80
  #     - 90
  #     - 100

  # - name: "room-32-32-4"
  #   label: Room
  #   scens:
  #     - even
  #     - random
  #   num_of_agents:
  #     - 10
  #     - 20
  #     - 30
  #     - 40
  #     - 50
  #     - 60
  #     - 70
  #     - 80
  #     - 90
  #     - 100

solvers:
  - name: "PBS1_min_runtime"
    label: "PBS(best)"
    color: "deepskyblue"
    marker: "o"

  - name: "PBS1_mid_runtime"
    label: "PBS(mid)"
    color: "green"
    marker: "s"
  
  - name: "PBS1_max_runtime"
    label: "PBS(worst)"
    color: "red"
    marker: "^"
