exp_path: "/home/rdaneel/my_exp_PBS0627/"
# exp_path: "/home/rdaneel/my_exp_socs2022/"
# exp_path: "/home/rdaneel/my_exp/"
ins_num: 50
time_limit: 60
set_title: true
set_legend: false
plot_ci: false
plot_std: false

maps:
  # - name: "10obs-20x20"
  #   label: $20\times20$ Grid ($10\%$ obstacles)
  #   scens:
  #     - hang
  #   num_of_agents:
  #     - 20
  #     - 30
  #     - 40
  #     - 50
  #     - 60
  #     - 70
  #     - 80
  #     - 90
  #     - 100

  # - name: "20x20"
  #   label: Empty $20\times20$ Grid
  #   scens:
  #     - hang
  #   num_of_agents:
  #     - 20
  #     - 30
  #     - 40
  #     - 50
  #     - 60
  #     - 70
  #     - 80
  #     - 90
  #     - 100

  - name: "brc202d"
    label: brc202d
    scens:
      - hang
    num_of_agents:
      - 20
      - 40
      - 60
      - 80
      - 100
      - 120
      - 140
      - 160

  # - name: "lak503d"
  #   label: lak503d
  #   scens:
  #     - hang
  #   num_of_agents:
  #     - 20
  #     - 40
  #     - 60
  #     - 80
  #     - 100

solvers:
  # - name: "PBS0"
  #   label: "PBS"
  #   color: "grey"
  #   marker: "P"

  - name: "PBS1"
    label: "PBS(Random)"
    color: "purple"
    marker: "d"

  - name: "PBS2"
    label: "PBS(First)"
    color: "gold"
    marker: "<"

  # - name: "PBS3"
  #   label: "PBS(Min PA)"
  #   color: 'deepskyblue'
  #   marker: 'o'

  # - name: "PBS4"
  #   label: "PBS(Max PA)"
  #   color: 'green'
  #   marker: 's'

  # - name: "PBS5"
  #   label: "PBS(BFS)"
  #   color: 'orange'
  #   marker: '*'

  # - name: "PBS6"
  #   label: "PBS(DFS)"
  #   color: 'pink'
  #   marker: 'H'

  - name: "PBS7"
    label: "PBS(Min cons)"
    color: 'red'
    marker: '^'

  - name: "PBS8"
    label: "PBS(Max cons)"
    color: 'brown'
    marker: 'X'