exp_path: "/home/rdaneel/my_exp/"
ins_num: 50
time_limit: 60
plot_ci: false

maps:
  - name: "20x20"
    label: Empty $20\times20$ Grid
    scens:
      - hang
    num_of_agents:
      - 10
      - 20
      - 30
      - 40
      - 50
      - 60
      - 70
      - 80
      - 90
      - 100

  # - name: "10obs-20x20"
  #   label: $20\times20$ Grid ($10\%$ obstacles)
  #   scens:
  #     - hang
  #   num_of_agents:
  #     - 10
  #     - 20
  #     - 30
  #     - 40
  #     - 50
  #     - 60
  #     - 70
  #     - 80
  #     - 90
  #     - 100

  # - name: "brc202d"
  #   label: brc202d
  #   scens:
  #     - hang
  #   num_of_agents:
  #     - 20
  #     - 40
  #     - 60
  #     - 80
  #     - 100
  #     - 120
  #     - 140
  #     - 160

  # - name: "lak503d"
  #   label: lak503d
  #   scens:
  #     - hang
  #   num_of_agents:
  #     - 20
  #     - 40
  #     - 60
  #     - 80
  #     - 100

solvers:
  # - name: "PBS0"
  #   label: "PBS"
  #   color: "grey"
  #   marker: "P"
  
  - name: "PBS1"
    label: "PBS(First)"
    color: "deepskyblue"
    marker: "o"

  - name: "PBS1a"
    label: "PBS(First2)"
    color: "blue"
    marker: "o"
  
  - name: "PBS6"
    label: "PBS(Earliest)"
    color: 'purple'
    marker: 'd'

  # - name: "PBS2"
  #   label: "PBS(Smallest)"
  #   color: 'green'
  #   marker: 's'

  # - name: "PBS4"
  #   label: "PBS(Largest w/o Internal first)"
  #   color: 'purple'
  #   marker: '>'

  - name: "PBS3"
    label: "PBS(Largest)"
    color: 'orange'
    marker: '^'