exp_path: "/home/rdaneel/my_exp/"
ins_num: 50
time_limit: 60
plot_ci: false

maps:
  # - name: "20x20"
  #   label: $20\times20$
  #   scens:
  #     - hang
  #   num_of_agents:
  #     - 10
  #     - 20
  #     - 30
  #     - 40
  #     - 50
  #     - 60
  #     - 70
  #     - 80
  #     - 90
  #     - 100

  # - name: "10obs-20x20"
  #   label: $20\times20$ ($10\%$ obstacles)
  #   scens:
  #     - hang
  #   num_of_agents:
  #     - 10
  #     - 20
  #     - 30
  #     - 40
  #     - 50
  #     - 60
  #     - 70
  #     - 80
  #     - 90
  #     - 100

  # - name: "brc202d"
  #   label: Brc202d
  #   scens:
  #     - hang
  #   num_of_agents:
  #     - 20
  #     - 40
  #     - 60
  #     - 80
  #     - 100
  #     - 120
  #     - 140
  #     - 160

  - name: "lak503d"
    label: Lak503d
    scens:
      - hang
    num_of_agents:
      - 20
      - 40
      - 60
      - 80
      - 100

solvers:
  # - name: "PBS0"
  #   label: "PBS"
  #   color: "grey"
  #   marker: "P"
  
  - name: "PBS1"
    label: "PBS(First)"
    color: "deepskyblue"
    marker: "o"

  - name: "PBS2"
    label: "PBS(S)"
    color: 'green'
    marker: 's'

  - name: "PBS3"
    label: "PBS(L)"
    color: 'orange'
    marker: '^'