exp_path: "/home/rdaneel/my_exp/"
ins_num: 25
time_limit: 60
plot_ci: false

maps:
  - name: "random-32-32-20"
    label: $32\times32$ ($20\%$ obstacle)
    scens:
      - even
    num_of_agents:
      - 20
      - 40
      - 40
      - 60
      - 80
      - 100

  # - name: "warehouse-20-40-10-2-1"
  #   label: Warehouse
  #   scens:
  #     - even
  #   num_of_agents:
  #     - 20
  #     - 40
  #     - 40
  #     - 60
  #     - 80
  #     - 100
  #     - 120
  #     - 140
  #     - 160

  # - name: "maze-32-32-2"
  #   label: Maze
  #   scens:
  #     - even
  #   num_of_agents:
  #     - 10
  #     - 20
  #     - 30
  #     - 40
  #     - 50
  #     - 60

  # - name: "room-32-32-4"
  #   label: Room
  #   scens:
  #     - even
  #   num_of_agents:
  #     - 10
  #     - 20
  #     - 30
  #     - 40
  #     - 50
  #     - 60
  #     - 70
  #     - 80
  #     - 90
  #     - 100

solvers:
  # - name: "PBS0"
  #   label: "PBS"
  #   color: "grey"
  #   marker: "P"
  
  - name: "PBS1"
    label: "PBS(First)"
    color: "deepskyblue"
    marker: "o"

  - name: "PBS2"
    label: "PBS(S)"
    color: 'green'
    marker: 's'
  
  - name: "PBS3"
    label: "PBS(L)"
    color: 'orange'
    marker: '^'
